//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation,
// v2.2.8-b130911.1802
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2017.02.22 at 02:46:33 AM MSK 
//


package xmlclasses;

import javax.xml.bind.annotation.*;
import javax.xml.datatype.XMLGregorianCalendar;
import java.math.BigInteger;


/**
 * <p>Java class for bitrix_person complex type.
 * <p>
 * <p>The following schema fragment specifies the expected content contained within this class.
 * <p>
 * <pre>
 * &lt;complexType name="bitrix_person">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="id" type="{http://www.w3.org/2001/XMLSchema}integer"/>
 *         &lt;element name="bitrix_id" type="{http://www.w3.org/2001/XMLSchema}integer"/>
 *         &lt;element name="firstname" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="middlename" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="lastname" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="email" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="phone" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="birthdate" type="{http://www.w3.org/2001/XMLSchema}date"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "bitrix_person", propOrder = {
		"id",
		"bitrixId",
		"firstname",
		"middlename",
		"lastname",
		"email",
		"phone",
		"birthdate"
})
public class BitrixPerson {
	
	@XmlElement(required = true)
	protected BigInteger id;
	@XmlElement(name = "bitrix_id", required = true)
	protected BigInteger bitrixId;
	@XmlElement(required = true)
	protected String firstname;
	protected String middlename;
	@XmlElement(required = true)
	protected String lastname;
	@XmlElement(required = true)
	protected String email;
	@XmlElement(required = true)
	protected String phone;
	@XmlElement(required = true)
	@XmlSchemaType(name = "date")
	protected XMLGregorianCalendar birthdate;
	
	/**
	 * Gets the value of the id property.
	 *
	 * @return possible object is
	 * {@link BigInteger }
	 */
	public BigInteger getId() {
		return id;
	}
	
	/**
	 * Sets the value of the id property.
	 *
	 * @param value allowed object is
	 *              {@link BigInteger }
	 */
	public void setId(BigInteger value) {
		this.id = value;
	}
	
	/**
	 * Gets the value of the bitrixId property.
	 *
	 * @return possible object is
	 * {@link BigInteger }
	 */
	public BigInteger getBitrixId() {
		return bitrixId;
	}
	
	/**
	 * Sets the value of the bitrixId property.
	 *
	 * @param value allowed object is
	 *              {@link BigInteger }
	 */
	public void setBitrixId(BigInteger value) {
		this.bitrixId = value;
	}
	
	/**
	 * Gets the value of the firstname property.
	 *
	 * @return possible object is
	 * {@link String }
	 */
	public String getFirstname() {
		return firstname;
	}
	
	/**
	 * Sets the value of the firstname property.
	 *
	 * @param value allowed object is
	 *              {@link String }
	 */
	public void setFirstname(String value) {
		this.firstname = value;
	}
	
	/**
	 * Gets the value of the middlename property.
	 *
	 * @return possible object is
	 * {@link String }
	 */
	public String getMiddlename() {
		return middlename;
	}
	
	/**
	 * Sets the value of the middlename property.
	 *
	 * @param value allowed object is
	 *              {@link String }
	 */
	public void setMiddlename(String value) {
		this.middlename = value;
	}
	
	/**
	 * Gets the value of the lastname property.
	 *
	 * @return possible object is
	 * {@link String }
	 */
	public String getLastname() {
		return lastname;
	}
	
	/**
	 * Sets the value of the lastname property.
	 *
	 * @param value allowed object is
	 *              {@link String }
	 */
	public void setLastname(String value) {
		this.lastname = value;
	}
	
	/**
	 * Gets the value of the email property.
	 *
	 * @return possible object is
	 * {@link String }
	 */
	public String getEmail() {
		return email;
	}
	
	/**
	 * Sets the value of the email property.
	 *
	 * @param value allowed object is
	 *              {@link String }
	 */
	public void setEmail(String value) {
		this.email = value;
	}
	
	/**
	 * Gets the value of the phone property.
	 *
	 * @return possible object is
	 * {@link String }
	 */
	public String getPhone() {
		return phone;
	}
	
	/**
	 * Sets the value of the phone property.
	 *
	 * @param value allowed object is
	 *              {@link String }
	 */
	public void setPhone(String value) {
		this.phone = value;
	}
	
	/**
	 * Gets the value of the birthdate property.
	 *
	 * @return possible object is
	 * {@link XMLGregorianCalendar }
	 */
	public XMLGregorianCalendar getBirthdate() {
		return birthdate;
	}
	
	/**
	 * Sets the value of the birthdate property.
	 *
	 * @param value allowed object is
	 *              {@link XMLGregorianCalendar }
	 */
	public void setBirthdate(XMLGregorianCalendar value) {
		this.birthdate = value;
	}
	
}
