//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation,
// v2.2.8-b130911.1802
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2017.02.22 at 02:46:33 AM MSK 
//


package xmlclasses;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for emailContent complex type.
 * <p>
 * <p>The following schema fragment specifies the expected content contained within this class.
 * <p>
 * <pre>
 * &lt;complexType name="emailContent">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="textContent" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "emailContent", propOrder = {
		"textContent"
})
public class EmailContent {
	
	@XmlElement(required = true)
	protected String textContent;
	
	/**
	 * Gets the value of the textContent property.
	 *
	 * @return possible object is
	 * {@link String }
	 */
	public String getTextContent() {
		return textContent;
	}
	
	/**
	 * Sets the value of the textContent property.
	 *
	 * @param value allowed object is
	 *              {@link String }
	 */
	public void setTextContent(String value) {
		this.textContent = value;
	}
	
}
