//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation,
// v2.2.8-b130911.1802
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2017.02.22 at 02:46:33 AM MSK 
//


package xmlclasses;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;
import java.math.BigInteger;


/**
 * <p>Java class for emailTemplate complex type.
 * <p>
 * <p>The following schema fragment specifies the expected content contained within this class.
 * <p>
 * <pre>
 * &lt;complexType name="emailTemplate">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="id" type="{http://www.w3.org/2001/XMLSchema}integer"/>
 *         &lt;element name="reason" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="contentTemplate" type="{http://DBClasses/CommonTypes}emailContent"/>
 *         &lt;element name="subject" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "emailTemplate", namespace = "http://DBClasses/EmailTypes", propOrder = {
		"id",
		"reason",
		"contentTemplate",
		"subject"
})
public class EmailTemplate {
	
	@XmlElement(required = true)
	protected BigInteger id;
	@XmlElement(required = true)
	protected String reason;
	@XmlElement(required = true)
	protected EmailContent contentTemplate;
	@XmlElement(required = true)
	protected String subject;
	
	/**
	 * Gets the value of the id property.
	 *
	 * @return possible object is
	 * {@link BigInteger }
	 */
	public BigInteger getId() {
		return id;
	}
	
	/**
	 * Sets the value of the id property.
	 *
	 * @param value allowed object is
	 *              {@link BigInteger }
	 */
	public void setId(BigInteger value) {
		this.id = value;
	}
	
	/**
	 * Gets the value of the reason property.
	 *
	 * @return possible object is
	 * {@link String }
	 */
	public String getReason() {
		return reason;
	}
	
	/**
	 * Sets the value of the reason property.
	 *
	 * @param value allowed object is
	 *              {@link String }
	 */
	public void setReason(String value) {
		this.reason = value;
	}
	
	/**
	 * Gets the value of the contentTemplate property.
	 *
	 * @return possible object is
	 * {@link EmailContent }
	 */
	public EmailContent getContentTemplate() {
		return contentTemplate;
	}
	
	/**
	 * Sets the value of the contentTemplate property.
	 *
	 * @param value allowed object is
	 *              {@link EmailContent }
	 */
	public void setContentTemplate(EmailContent value) {
		this.contentTemplate = value;
	}
	
	/**
	 * Gets the value of the subject property.
	 *
	 * @return possible object is
	 * {@link String }
	 */
	public String getSubject() {
		return subject;
	}
	
	/**
	 * Sets the value of the subject property.
	 *
	 * @param value allowed object is
	 *              {@link String }
	 */
	public void setSubject(String value) {
		this.subject = value;
	}
	
}
