//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2017.02.22 at 02:46:33 AM MSK 
//


package xmlclasses;

import java.math.BigInteger;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlSchemaType;
import javax.xml.bind.annotation.XmlType;
import javax.xml.datatype.XMLGregorianCalendar;


/**
 * <p>Java class for email complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="email">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="id" type="{http://www.w3.org/2001/XMLSchema}integer"/>
 *         &lt;element name="addressee_id" type="{http://www.w3.org/2001/XMLSchema}integer"/>
 *         &lt;element name="sender_id" type="{http://www.w3.org/2001/XMLSchema}integer"/>
 *         &lt;element name="reason_id" type="{http://www.w3.org/2001/XMLSchema}integer"/>
 *         &lt;element name="sended_at" type="{http://www.w3.org/2001/XMLSchema}dateTime"/>
 *         &lt;element name="content" type="{http://DBClasses/CommonTypes}emailContent"/>
 *         &lt;element name="subject" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "email", namespace = "http://DBClasses/EmailTypes", propOrder = {
    "id",
    "addresseeId",
    "senderId",
    "reasonId",
    "sendedAt",
    "content",
    "subject"
})
public class Email {

    @XmlElement(required = true)
    protected BigInteger id;
    @XmlElement(name = "addressee_id", required = true)
    protected BigInteger addresseeId;
    @XmlElement(name = "sender_id", required = true)
    protected BigInteger senderId;
    @XmlElement(name = "reason_id", required = true)
    protected BigInteger reasonId;
    @XmlElement(name = "sended_at", required = true)
    @XmlSchemaType(name = "dateTime")
    protected XMLGregorianCalendar sendedAt;
    @XmlElement(required = true)
    protected EmailContent content;
    @XmlElement(required = true)
    protected String subject;

    /**
     * Gets the value of the id property.
     * 
     * @return
     *     possible object is
     *     {@link BigInteger }
     *     
     */
    public BigInteger getId() {
        return id;
    }

    /**
     * Sets the value of the id property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigInteger }
     *     
     */
    public void setId(BigInteger value) {
        this.id = value;
    }

    /**
     * Gets the value of the addresseeId property.
     * 
     * @return
     *     possible object is
     *     {@link BigInteger }
     *     
     */
    public BigInteger getAddresseeId() {
        return addresseeId;
    }

    /**
     * Sets the value of the addresseeId property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigInteger }
     *     
     */
    public void setAddresseeId(BigInteger value) {
        this.addresseeId = value;
    }

    /**
     * Gets the value of the senderId property.
     * 
     * @return
     *     possible object is
     *     {@link BigInteger }
     *     
     */
    public BigInteger getSenderId() {
        return senderId;
    }

    /**
     * Sets the value of the senderId property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigInteger }
     *     
     */
    public void setSenderId(BigInteger value) {
        this.senderId = value;
    }

    /**
     * Gets the value of the reasonId property.
     * 
     * @return
     *     possible object is
     *     {@link BigInteger }
     *     
     */
    public BigInteger getReasonId() {
        return reasonId;
    }

    /**
     * Sets the value of the reasonId property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigInteger }
     *     
     */
    public void setReasonId(BigInteger value) {
        this.reasonId = value;
    }

    /**
     * Gets the value of the sendedAt property.
     * 
     * @return
     *     possible object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public XMLGregorianCalendar getSendedAt() {
        return sendedAt;
    }

    /**
     * Sets the value of the sendedAt property.
     * 
     * @param value
     *     allowed object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public void setSendedAt(XMLGregorianCalendar value) {
        this.sendedAt = value;
    }

    /**
     * Gets the value of the content property.
     * 
     * @return
     *     possible object is
     *     {@link EmailContent }
     *     
     */
    public EmailContent getContent() {
        return content;
    }

    /**
     * Sets the value of the content property.
     * 
     * @param value
     *     allowed object is
     *     {@link EmailContent }
     *     
     */
    public void setContent(EmailContent value) {
        this.content = value;
    }

    /**
     * Gets the value of the subject property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getSubject() {
        return subject;
    }

    /**
     * Sets the value of the subject property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setSubject(String value) {
        this.subject = value;
    }

}
