//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation,
// v2.2.8-b130911.1802
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2017.02.22 at 02:46:33 AM MSK 
//


package xmlclasses;

import javax.xml.bind.JAXBElement;
import javax.xml.bind.annotation.XmlElementDecl;
import javax.xml.bind.annotation.XmlRegistry;
import javax.xml.namespace.QName;


/**
 * This object contains factory methods for each
 * Java content interface and Java element interface
 * generated in the xmlclasses package.
 * <p>An ObjectFactory allows you to programatically
 * construct new instances of the Java representation
 * for XML content. The Java representation of XML
 * content can consist of schema derived interfaces
 * and classes representing the binding of schema
 * type definitions, element declarations and model
 * groups.  Factory methods for each of these are
 * provided in this class.
 */
@XmlRegistry
public class ObjectFactory {
	
	private final static QName _EmailTemplate_QNAME = new QName("http://DBClasses/EmailTypes", "emailTemplate");
	private final static QName _Employee_QNAME = new QName("http://DBClasses/EmailTypes", "employee");
	private final static QName _Enrollee_QNAME = new QName("http://DBClasses/EmailTypes", "enrollee");
	private final static QName _SendedEmail_QNAME = new QName("http://DBClasses/EmailTypes", "sendedEmail");
	
	/**
	 * Create a new ObjectFactory that can be used to create new instances of schema derived classes for package:
	 * xmlclasses
	 */
	public ObjectFactory() {
	}
	
	/**
	 * Create an instance of {@link EmailTemplate }
	 */
	public EmailTemplate createEmailTemplate() {
		return new EmailTemplate();
	}
	
	/**
	 * Create an instance of {@link Email }
	 */
	public Email createEmail() {
		return new Email();
	}
	
	/**
	 * Create an instance of {@link Employee }
	 */
	public Employee createEmployee() {
		return new Employee();
	}
	
	/**
	 * Create an instance of {@link BitrixPerson }
	 */
	public BitrixPerson createBitrixPerson() {
		return new BitrixPerson();
	}
	
	/**
	 * Create an instance of {@link EmailContent }
	 */
	public EmailContent createEmailContent() {
		return new EmailContent();
	}
	
	/**
	 * Create an instance of {@link JAXBElement }{@code <}{@link EmailTemplate }{@code >}}
	 */
	@XmlElementDecl(namespace = "http://DBClasses/EmailTypes", name = "emailTemplate")
	public JAXBElement<EmailTemplate> createEmailTemplate(EmailTemplate value) {
		return new JAXBElement<EmailTemplate>(_EmailTemplate_QNAME, EmailTemplate.class, null, value);
	}
	
	/**
	 * Create an instance of {@link JAXBElement }{@code <}{@link Employee }{@code >}}
	 */
	@XmlElementDecl(namespace = "http://DBClasses/EmailTypes", name = "employee")
	public JAXBElement<Employee> createEmployee(Employee value) {
		return new JAXBElement<Employee>(_Employee_QNAME, Employee.class, null, value);
	}
	
	/**
	 * Create an instance of {@link JAXBElement }{@code <}{@link BitrixPerson }{@code >}}
	 */
	@XmlElementDecl(namespace = "http://DBClasses/EmailTypes", name = "enrollee")
	public JAXBElement<BitrixPerson> createEnrollee(BitrixPerson value) {
		return new JAXBElement<BitrixPerson>(_Enrollee_QNAME, BitrixPerson.class, null, value);
	}
	
	/**
	 * Create an instance of {@link JAXBElement }{@code <}{@link Email }{@code >}}
	 */
	@XmlElementDecl(namespace = "http://DBClasses/EmailTypes", name = "sendedEmail")
	public JAXBElement<Email> createSendedEmail(Email value) {
		return new JAXBElement<Email>(_SendedEmail_QNAME, Email.class, null, value);
	}
	
}
